CREATE DATABASE "GerenciaBanco"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE IF NOT EXISTS public.USUARIO
(
	ID_USUARIO integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    USUARIO text COLLATE pg_catalog."default",
    SENHA text COLLATE pg_catalog."default",
	NOME text COLLATE pg_catalog."default",
	SOBRENOME text COLLATE pg_catalog."default",
	CPF text COLLATE pg_catalog."default",
    EMAIL text COLLATE pg_catalog."default",
    TELEFONE text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS PUBLIC.MOVIMENTO
(
	ID_MOVIMENTO integer NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	TIPOMOVIMENTO text COLLATE pg_catalog."default",
	ID_USUARIO integer,
	QUANTIDADEMOVIMENTADA real,
	CONSTRAINT ID_MOVIMENTO PRIMARY KEY (ID_MOVIMENTO),
	CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES public.USUARIO (ID_USUARIO) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.SALDO
(    
	ID_USUARIO integer,
    VALOR real,
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES public.USUARIO (ID_USUARIO) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);